// ============================================================================
// KONFIGURACJA SZAFEK
// Edytuj ten plik, żeby dodawać nowe typy szafek
// ============================================================================

export const CABINET_TYPES = [
  {
    id: 'bottom',
    name: 'Szafka dolna',
    category: 'dolne',
    basePrice: 180,
    defaultHeight: 720,
    defaultWidth: 600,
    defaultDepth: 510,
    minHeight: 200,
    maxHeight: 900,
    minWidth: 150,
    maxWidth: 1200,
    minDepth: 200,
    maxDepth: 700,
    hasLegs: true,
    description: 'Standardowa szafka dolna pod blat',
  },
  {
    id: 'bottom_sink',
    name: 'Szafka zlewozmywakowa',
    category: 'dolne',
    basePrice: 220,
    defaultHeight: 720,
    defaultWidth: 800,
    defaultDepth: 510,
    minHeight: 200,
    maxHeight: 900,
    minWidth: 600,
    maxWidth: 1200,
    minDepth: 200,
    maxDepth: 700,
    hasLegs: true,
    hasFrontsDefault: true,
    description: 'Szafka pod zlewozmywak z wycięciem',
  },
  {
    id: 'bottom_drawers',
    name: 'Szafka z szufladami',
    category: 'dolne',
    basePrice: 280,
    defaultHeight: 720,
    defaultWidth: 600,
    defaultDepth: 510,
    minHeight: 400,
    maxHeight: 900,
    minWidth: 300,
    maxWidth: 900,
    minDepth: 200,
    maxDepth: 700,
    hasLegs: true,
    hasDrawers: true,
    drawerOptions: [2, 3, 4, 5],
    description: 'Szafka dolna z szufladami',
  },
  {
    id: 'bottom_corner',
    name: 'Szafka narożna',
    category: 'dolne',
    basePrice: 350,
    defaultHeight: 720,
    defaultWidth: 900,
    defaultDepth: 900,
    minHeight: 200,
    maxHeight: 900,
    minWidth: 800,
    maxWidth: 1100,
    minDepth: 800,
    maxDepth: 1100,
    hasLegs: true,
    isCorner: true,
    description: 'Narożna szafka dolna 90°',
  },
  {
    id: 'top',
    name: 'Szafka górna',
    category: 'górne',
    basePrice: 150,
    defaultHeight: 720,
    defaultWidth: 600,
    defaultDepth: 350,
    minHeight: 300,
    maxHeight: 1000,
    minWidth: 150,
    maxWidth: 1200,
    minDepth: 200,
    maxDepth: 400,
    hasLegs: false,
    description: 'Standardowa szafka wisząca',
  },
  {
    id: 'top_hood',
    name: 'Szafka okapowa',
    category: 'górne',
    basePrice: 180,
    defaultHeight: 400,
    defaultWidth: 600,
    defaultDepth: 350,
    minHeight: 200,
    maxHeight: 600,
    minWidth: 500,
    maxWidth: 900,
    minDepth: 200,
    maxDepth: 400,
    hasLegs: false,
    hasHoodCutout: true,
    description: 'Szafka nad okap z wycięciem',
  },
  {
    id: 'top_glass',
    name: 'Szafka z witryną',
    category: 'górne',
    basePrice: 250,
    defaultHeight: 720,
    defaultWidth: 600,
    defaultDepth: 350,
    minHeight: 400,
    maxHeight: 1000,
    minWidth: 300,
    maxWidth: 900,
    minDepth: 200,
    maxDepth: 400,
    hasLegs: false,
    hasGlassFront: true,
    description: 'Szafka z przeszklonymi drzwiami',
  },
  {
    id: 'tall',
    name: 'Słupek wysoki',
    category: 'słupki',
    basePrice: 280,
    defaultHeight: 2000,
    defaultWidth: 600,
    defaultDepth: 560,
    minHeight: 1400,
    maxHeight: 2400,
    minWidth: 400,
    maxWidth: 800,
    minDepth: 300,
    maxDepth: 700,
    hasLegs: true,
    description: 'Wysoki słupek gospodarczy',
  },
  {
    id: 'tall_oven',
    name: 'Słupek na piekarnik',
    category: 'słupki',
    basePrice: 350,
    defaultHeight: 2000,
    defaultWidth: 600,
    defaultDepth: 560,
    minHeight: 1400,
    maxHeight: 2400,
    minWidth: 560,
    maxWidth: 700,
    minDepth: 500,
    maxDepth: 620,
    hasLegs: true,
    hasOvenCutout: true,
    ovenHeight: 600,
    description: 'Słupek z wnęką na piekarnik',
  },
  {
    id: 'tall_fridge',
    name: 'Zabudowa lodówki',
    category: 'słupki',
    basePrice: 320,
    defaultHeight: 2200,
    defaultWidth: 600,
    defaultDepth: 600,
    minHeight: 1800,
    maxHeight: 2400,
    minWidth: 560,
    maxWidth: 700,
    minDepth: 560,
    maxDepth: 700,
    hasLegs: true,
    hasFridgeCutout: true,
    description: 'Zabudowa na lodówkę do wbudowania',
  },
];

export const CABINET_CATEGORIES = [
  { id: 'dolne', name: 'Szafki dolne', icon: 'bottom' },
  { id: 'górne', name: 'Szafki górne', icon: 'top' },
  { id: 'słupki', name: 'Słupki wysokie', icon: 'tall' },
];

// ============================================================================
// JAK DODAĆ NOWY TYP SZAFKI:
// ============================================================================
// 1. Skopiuj jeden z obiektów powyżej
// 2. Zmień 'id' na unikalny (np. 'bottom_cargo')
// 3. Ustaw 'name' - nazwa wyświetlana
// 4. Ustaw 'category' - musi być: 'dolne', 'górne' lub 'słupki'
// 5. Ustaw 'basePrice' - cena bazowa
// 6. Ustaw domyślne i min/max wymiary
// 7. Dodaj opcjonalne flagi (hasDrawers, hasOvenCutout, itd.)
// ============================================================================
